### ISSUE TITLE
Publish PDFs to GH-PAGES Branch

### ISSUE THREAD

**Issue by ian-bloom** [rchain/legaldocs#1]
The [Private Sale](https://privatesaleinfo.rchain.coop/documents-1/) Website is linking to pdf documents in this repo.

Rather than rendering them inside of GitHub, they can be rendered **directly** in your browser. This can be done by publishing the pdf to the repo's gh-pages branch.

**Comment by dckc** [comment]
Ooh... that's half the battle of putting them in the **rchain.coop** domain; cf https://github.com/rchain/bounties/issues/411
